#!/bin/bash
#
# PlexIQ v5.3.2 - Setup Wizard
# Production Ready Edition
#
# This script will guide you through setting up PlexIQ for the first time.
#

set -e  # Exit on error

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
GOLD='\033[38;5;220m'
NC='\033[0m' # No Color
BOLD='\033[1m'

# Clear screen and show header
clear
echo ""
echo -e "${GOLD}${BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${GOLD}${BOLD}           PlexIQ v5.3.2 - Chicago Edition            ${NC}"
echo -e "${GOLD}${BOLD}           🌭 Setup Wizard - GET YOUR HOTDOGS! 🌭       ${NC}"
echo -e "${GOLD}${BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo -e "${BLUE}This wizard will help you set up PlexIQ in minutes.${NC}"
echo ""

# Function to print success
success() {
    echo -e "${GREEN}✓${NC} $1"
}

# Function to print error
error() {
    echo -e "${RED}✗${NC} $1"
}

# Function to print info
info() {
    echo -e "${BLUE}ℹ${NC} $1"
}

# Function to print warning
warn() {
    echo -e "${YELLOW}⚠${NC} $1"
}

# Check Node.js
echo -e "${BOLD}Step 1: Checking Prerequisites${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

if ! command -v node &> /dev/null; then
    error "Node.js is not installed"
    echo ""
    echo "Please install Node.js 18+ from: https://nodejs.org/"
    echo "Then run this script again."
    exit 1
fi

NODE_VERSION=$(node --version | cut -d'v' -f2 | cut -d'.' -f1)
if [ "$NODE_VERSION" -lt 18 ]; then
    error "Node.js version 18 or higher is required (found v$NODE_VERSION)"
    echo "Please upgrade Node.js: https://nodejs.org/"
    exit 1
fi

success "Node.js $(node --version) found"

if ! command -v npm &> /dev/null; then
    error "npm is not installed"
    exit 1
fi

success "npm $(npm --version) found"
echo ""

# Install dependencies
echo -e "${BOLD}Step 2: Installing Dependencies${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

cd web
if [ -f "package-lock.json" ]; then
    info "Cleaning previous installation..."
    rm -rf node_modules package-lock.json
fi

info "Installing web interface dependencies..."
npm install

cd ..
if [ ! -d "node_modules" ]; then
    info "Installing root dependencies (TUI)..."
    npm install
fi

success "All dependencies installed"
echo ""

# Configuration
echo -e "${BOLD}Step 3: Plex Configuration${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

CONFIG_FILE="web/.env.local"

# Check if config already exists
if [ -f "$CONFIG_FILE" ]; then
    warn "Configuration file already exists: $CONFIG_FILE"
    echo ""
    read -p "Do you want to reconfigure? (y/N): " -n 1 -r
    echo ""
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        info "Keeping existing configuration"
        SKIP_CONFIG=true
    else
        SKIP_CONFIG=false
    fi
else
    SKIP_CONFIG=false
fi

if [ "$SKIP_CONFIG" = false ]; then
    echo "Let's set up your Plex connection."
    echo ""

    # Plex Host
    echo -e "${GOLD}Plex Server Address${NC}"
    echo "Examples:"
    echo "  • http://192.168.1.100:32400"
    echo "  • http://localhost:32400"
    echo "  • http://10.0.0.10:32400"
    echo ""
    read -p "Enter your Plex server address: " PLEX_HOST

    # Validate Plex Host
    if [[ ! $PLEX_HOST =~ ^https?:// ]]; then
        PLEX_HOST="http://$PLEX_HOST"
    fi

    echo ""

    # Plex Token
    echo -e "${GOLD}Plex Authentication Token${NC}"
    echo "To find your Plex token:"
    echo "  1. Sign in to Plex Web App"
    echo "  2. Play any movie/show"
    echo "  3. Click ⚙ (Settings) > Get Info > View XML"
    echo "  4. Look for X-Plex-Token in the URL"
    echo ""
    echo "Or visit: https://support.plex.tv/articles/204059436"
    echo ""
    read -p "Enter your Plex token: " PLEX_TOKEN

    echo ""

    # Optional APIs
    echo -e "${GOLD}Optional: Enhanced Metadata (TMDb/OMDb)${NC}"
    echo "PlexIQ can enrich metadata using external APIs."
    echo "This is optional - you can skip it and use Plex data only."
    echo ""
    read -p "Do you want to configure API keys? (y/N): " -n 1 -r
    echo ""

    if [[ $REPLY =~ ^[Yy]$ ]]; then
        echo ""
        echo "TMDb API Key (free from: https://www.themoviedb.org/settings/api)"
        read -p "TMDb API Key (or press Enter to skip): " TMDB_KEY

        echo ""
        echo "OMDb API Key (free from: http://www.omdbapi.com/apikey.aspx)"
        read -p "OMDb API Key (or press Enter to skip): " OMDB_KEY
    fi

    # Write config file
    echo ""
    info "Writing configuration to $CONFIG_FILE..."

    cat > "$CONFIG_FILE" << EOF
# PlexIQ v5.3.2 Configuration
# Generated by setup wizard on $(date)

# Plex Server Configuration (Required)
PLEX_HOST=$PLEX_HOST
PLEX_TOKEN=$PLEX_TOKEN

# Optional: Enhanced Metadata APIs
EOF

    if [ -n "$TMDB_KEY" ]; then
        echo "TMDB_API_KEY=$TMDB_KEY" >> "$CONFIG_FILE"
    else
        echo "# TMDB_API_KEY=your_key_here" >> "$CONFIG_FILE"
    fi

    if [ -n "$OMDB_KEY" ]; then
        echo "OMDB_API_KEY=$OMDB_KEY" >> "$CONFIG_FILE"
    else
        echo "# OMDB_API_KEY=your_key_here" >> "$CONFIG_FILE"
    fi

    cat >> "$CONFIG_FILE" << EOF

# Session Configuration
NEXT_PUBLIC_SESSION_PERSIST=true

# Demo Library Configuration
NEXT_PUBLIC_DEMO_ENABLED=true
EOF

    success "Configuration saved"
fi

echo ""

# Test Plex connection
echo -e "${BOLD}Step 4: Testing Plex Connection${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Load config
if [ -f "$CONFIG_FILE" ]; then
    source "$CONFIG_FILE"

    info "Testing connection to $PLEX_HOST..."

    if curl -s -f "${PLEX_HOST}/?X-Plex-Token=${PLEX_TOKEN}" > /dev/null 2>&1; then
        success "Plex connection successful!"
    else
        warn "Could not connect to Plex server"
        echo ""
        echo "This might be okay if:"
        echo "  • Plex is not running right now"
        echo "  • You're configuring for a different machine"
        echo "  • Firewall is blocking the connection"
        echo ""
        echo "You can test your connection manually:"
        echo "  curl ${PLEX_HOST}/?X-Plex-Token=${PLEX_TOKEN}"
        echo ""
    fi
else
    warn "Configuration file not found, skipping connection test"
fi

echo ""

# Setup complete
echo ""
echo -e "${GREEN}${BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${GREEN}${BOLD}              🎉 Setup Complete! 🎉                    ${NC}"
echo -e "${GREEN}${BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo -e "${BOLD}What's Next?${NC}"
echo ""
echo "1. Start the Web Interface:"
echo -e "   ${GOLD}cd web && npm run dev${NC}"
echo "   Then open: http://localhost:3000"
echo ""
echo "2. Or start the Terminal Interface:"
echo -e "   ${GOLD}npm run tui${NC}"
echo ""
echo -e "${BLUE}${BOLD}Pro Tips:${NC}"
echo "  🧪 Try the Demo Library first (safe testing environment)"
echo "  🌭 Drag the hotdog slider to set deletion threshold"
echo "  ★ Star items to make them untouchable"
echo "  🛡️ Always start with Dry Run mode (default)"
echo ""
echo -e "${YELLOW}${BOLD}⚠️  IMPORTANT SAFETY REMINDER${NC}"
echo "  • Test with Demo Library before using real libraries"
echo "  • Always use Dry Run mode first"
echo "  • Star anything you want to keep forever"
echo "  • Ratings ≥ 8.0 are automatically protected"
echo "  • Triple confirmation required for live deletion"
echo ""
echo -e "${GOLD}Need help? support@itwerks.net${NC}"
echo ""
echo -e "${GOLD}${BOLD}GET YOUR HOTDOGS! 🌭🌭🌭${NC}"
echo ""
